services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""  # sem senha
      MYSQL_DATABASE: banco_escolar
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask_app:
    build: .
    container_name: flask_container
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: banco_escolar
    depends_on:
      - mysql
    volumes:
      - .:/apis

volumes:
  mysql_data:
